2015-02-13 16:03:19 Error: [Cake\Controller\Exception\MissingActionException] Action ArticlesController::view() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ArticlesController',
  'action' => 'view',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake3blog/articles/view/1
Stack Trace:
#0 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#2 C:\xampp\htdocs\cake3blog\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-02-13 17:58:00 Error: Fatal Error (1): Call to a member function format() on a non-object in [C:\xampp\htdocs\cake3blog\src\Template\Articles\view.ctp, line 23]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-02-13 17:58:00 Error: [Cake\Error\FatalErrorException] Call to a member function format() on a non-object
Request URL: /cake3blog/articles/view/1
Stack Trace:
#0 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 23)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-02-13 17:58:40 Error: Fatal Error (1): Call to a member function format() on a non-object in [C:\xampp\htdocs\cake3blog\src\Template\Articles\view.ctp, line 23]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-02-13 17:58:40 Error: [Cake\Error\FatalErrorException] Call to a member function format() on a non-object
Request URL: /cake3blog/articles/view/1
Stack Trace:
#0 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 23)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-02-13 18:00:31 Error: Fatal Error (1): Call to a member function format() on a non-object in [C:\xampp\htdocs\cake3blog\src\Template\Articles\view.ctp, line 23]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-02-13 18:00:31 Error: [Cake\Error\FatalErrorException] Call to a member function format() on a non-object
Request URL: /cake3blog/articles/view/2
Stack Trace:
#0 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 23)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-02-13 18:00:43 Error: Fatal Error (1): Call to a member function format() on a non-object in [C:\xampp\htdocs\cake3blog\src\Template\Articles\view.ctp, line 23]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-02-13 18:00:43 Error: [Cake\Error\FatalErrorException] Call to a member function format() on a non-object
Request URL: /cake3blog/articles/view/2
Stack Trace:
#0 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 23)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-02-13 18:02:22 Error: Fatal Error (1): Call to a member function format() on a non-object in [C:\xampp\htdocs\cake3blog\src\Template\Articles\view.ctp, line 23]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-02-13 18:02:22 Error: [Cake\Error\FatalErrorException] Call to a member function format() on a non-object
Request URL: /cake3blog/articles/view/2
Stack Trace:
#0 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 23)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-02-13 18:34:00 Error: [Cake\View\Exception\MissingTemplateException] Template file "Articles\add.ctp" is missing.
Exception Attributes: array (
  'file' => 'Articles\\add.ctp',
)
Request URL: /cake3blog/articles/add
Stack Trace:
#0 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\View\View.php(460): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Controller\Controller.php(576): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#4 C:\xampp\htdocs\cake3blog\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2015-02-13 20:48:15 Error: [PDOException] SQLSTATE[HY000] [1045] Access denied for user 'my_app'@'localhost' (using password: YES)
Request URL: /cake3blog/
Stack Trace:
#0 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Database\Driver\PDODriverTrait.php(48): PDO->__construct('mysql:host=loca...', 'my_app', 'secret', Array)
#1 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Database\Driver\Mysql.php(86): Cake\Database\Driver\Mysql->_connect('mysql:host=loca...', Array)
#2 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Database\Schema\BaseSchema.php(46): Cake\Database\Driver\Mysql->connect()
#3 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Database\Dialect\MysqlDialectTrait.php(62): Cake\Database\Schema\BaseSchema->__construct(Object(Cake\Database\Driver\Mysql))
#4 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Database\Schema\Collection.php(52): Cake\Database\Driver\Mysql->schemaDialect()
#5 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Database\Schema\CachedCollection.php(44): Cake\Database\Schema\Collection->__construct(Object(Cake\Database\Connection))
#6 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Database\Connection.php(319): Cake\Database\Schema\CachedCollection->__construct(Object(Cake\Database\Connection), true)
#7 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\ORM\Table.php(410): Cake\Database\Connection->schemaCollection()
#8 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\ORM\Query.php(140): Cake\ORM\Table->schema()
#9 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\ORM\Query.php(122): Cake\ORM\Query->addDefaultTypes(Object(App\Model\Table\ArticlesTable))
#10 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\ORM\Table.php(1120): Cake\ORM\Query->__construct(Object(Cake\Database\Connection), Object(App\Model\Table\ArticlesTable))
#11 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\ORM\Table.php(869): Cake\ORM\Table->query()
#12 C:\xampp\htdocs\cake3blog\src\Controller\ArticlesController.php(29): Cake\ORM\Table->find('all')
#13 [internal function]: App\Controller\ArticlesController->index()
#14 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Controller\Controller.php(405): call_user_func_array(Array, Array)
#15 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#16 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#17 C:\xampp\htdocs\cake3blog\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#18 {main}


2015-02-16 16:21:10 Error: Fatal Error (1): Call to a member function allow() on boolean in [C:\xampp\htdocs\cake3blog\src\Controller\UsersController.php, line 33]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-02-16 16:21:10 Error: [Cake\Error\FatalErrorException] Call to a member function allow() on boolean
Request URL: /cake3blog/users
Stack Trace:
#0 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 33)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-02-16 17:02:39 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Categories could not be found.
Exception Attributes: array (
  'class' => 'Categories',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cake3blog/categories
Stack Trace:
#0 C:\xampp\htdocs\cake3blog\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-02-16 17:58:40 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Categories could not be found.
Exception Attributes: array (
  'class' => 'Categories',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cake3blog/categories
Stack Trace:
#0 C:\xampp\htdocs\cake3blog\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-02-16 21:42:58 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in [C:\xampp\htdocs\cake3blog\src\Controller\CategoriesController.php, line 111]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-02-16 21:42:59 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']'
Request URL: /cake3blog/categories
Stack Trace:
#0 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 111)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-02-16 21:43:26 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in [C:\xampp\htdocs\cake3blog\src\Template\Categories\index.ctp, line 37]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-02-16 21:43:26 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']'
Request URL: /cake3blog/categories
Stack Trace:
#0 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 37)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-02-16 21:50:50 Error: Fatal Error (1): Call to a member function allow() on boolean in [C:\xampp\htdocs\cake3blog\src\Controller\UsersController.php, line 33]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-02-16 21:50:51 Error: [Cake\Error\FatalErrorException] Call to a member function allow() on boolean
Request URL: /cake3blog/users/
Stack Trace:
#0 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 33)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-02-16 21:50:51 Error: Fatal Error (1): Call to a member function allow() on boolean in [C:\xampp\htdocs\cake3blog\src\Controller\UsersController.php, line 33]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-02-16 21:50:51 Error: [Cake\Error\FatalErrorException] Call to a member function allow() on boolean
Request URL: /cake3blog/users/
Stack Trace:
#0 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 33)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-02-16 21:50:52 Error: Fatal Error (1): Call to a member function allow() on boolean in [C:\xampp\htdocs\cake3blog\src\Controller\UsersController.php, line 33]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-02-16 21:50:53 Error: [Cake\Error\FatalErrorException] Call to a member function allow() on boolean
Request URL: /cake3blog/users/
Stack Trace:
#0 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 33)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-02-16 21:50:54 Error: Fatal Error (1): Call to a member function allow() on boolean in [C:\xampp\htdocs\cake3blog\src\Controller\UsersController.php, line 33]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-02-16 21:50:54 Error: [Cake\Error\FatalErrorException] Call to a member function allow() on boolean
Request URL: /cake3blog/users/
Stack Trace:
#0 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 33)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-02-16 21:50:56 Error: Fatal Error (1): Call to a member function allow() on boolean in [C:\xampp\htdocs\cake3blog\src\Controller\UsersController.php, line 33]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-02-16 21:50:56 Error: [Cake\Error\FatalErrorException] Call to a member function allow() on boolean
Request URL: /cake3blog/users/
Stack Trace:
#0 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 33)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-02-16 21:50:58 Error: Fatal Error (1): Call to a member function allow() on boolean in [C:\xampp\htdocs\cake3blog\src\Controller\UsersController.php, line 33]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-02-16 21:50:58 Error: [Cake\Error\FatalErrorException] Call to a member function allow() on boolean
Request URL: /cake3blog/users/
Stack Trace:
#0 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 33)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-02-16 21:51:00 Error: Fatal Error (1): Call to a member function allow() on boolean in [C:\xampp\htdocs\cake3blog\src\Controller\UsersController.php, line 33]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-02-16 21:51:00 Error: [Cake\Error\FatalErrorException] Call to a member function allow() on boolean
Request URL: /cake3blog/users/
Stack Trace:
#0 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 33)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-02-16 21:51:02 Error: Fatal Error (1): Call to a member function allow() on boolean in [C:\xampp\htdocs\cake3blog\src\Controller\UsersController.php, line 33]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-02-16 21:51:02 Error: [Cake\Error\FatalErrorException] Call to a member function allow() on boolean
Request URL: /cake3blog/users/
Stack Trace:
#0 C:\xampp\htdocs\cake3blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 33)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


